name: sentinel_world
version: "1.0.0"
config-version: 2

profile: sentinel_world

model-paths: ["models"]
seed-paths: ["seeds"]

seeds:
  sentinel_world:
    +schema: raw

models:
  sentinel_world:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
